### ISSUE TITLE
Ability to Search for Active Sales of a Specific Moment

### ISSUE THREAD

**Issue by abe-austin** [dapperlabs/nba-smart-contracts#130]
The SaleCollection provides access to all of the moments that a specific user has listed, and MomentListed can be used to retrieve all of the recently listed moments by any user, however it does not appear that there is any way to retrieve all of the for-sale moments of a specific play.

I suppose that a developer could repeatedly check for new MomentListed, MomentWithdrawn, and MomentPurchased events, and use those to update their own database of all the moments that are currently for sale, though that would be tedious and only accurate to the point that they launched their code.

Am I missing an already-existing function to retrieve all of the listed moments in a specific play, or is there any plan to add this endpoint in the future?

**Comment by joshuahannan** [comment]
The Top Shot graphQL API might provide this as an endpoint, but this is currently not possible on-chain because user's sales are all stored in their accounts. There is no central record of sales on chain, which is kind of a feature, not a bug. We don't think it should necessarily be possible to query all of this on-chain. It is certainly possible to add something like this, but we would need a lot more discussion and convincing before adding it

**Comment by bder222** [comment]
Is there any documentation available on the graphQL API?

**Comment by joshuahannan** [comment]
@bder222 These links might be useful!
https://support.nbatopshot.com/hc/en-us/articles/360063072193-Top-Shot-APIs
https://documenter.getpostman.com/view/7186182/TzJrBeRJ
