### ISSUE TITLE
Need clarification, whether I can use smart contracts legally.

### ISSUE THREAD

**Issue by UCT10** [dapperlabs/nba-smart-contracts#99]
Good day. I'm searching for ways to automatize my Top Shot trading. I've seen in Dapper Terms of Use recently that interaction with Dapper via transactions (interaction with blockchain) is prohibited. Now I can't find that phrase in ToS. I want to clarify whether I can interact with Flow blockchain directly. For now, it's the Dapper who controls the private keys. Is it allowed to interact with Top Shot smart contracts? To trade inside the blockchain from addresses that weren't created inside the Dapper Accounts service? Can I actually trade from such accounts? Can I request the private key from my account?
Thank you!

**Comment by UCT10** [comment]
@psiemens @joshuahannan @10thfloor

**Comment by joshuahannan** [comment]
@UCT10 Dapper Wallet currently does not allow users to export their private keys, so currently you aren't able to submit your own transactions outside of the top shot UI. You'll be able to create your own accounts soon though and submit from there! I'm gonna close this issue though because it doesn't really belong in the top shot smart contract discord.
